apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        volumeMounts:
        - name: nginx-vol
          mountPath: /app
        command: 
        - git
        - clone
        - https://github.com/javsalgar/http-example
        - /app
      containers:
      - name: nginx
        image: bitnami/nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-vol
          mountPath: /app
      # Sidecar
      - name: git-pull
        image: alpine/git
        volumeMounts:
        - name: nginx-vol
          mountPath: /app
        command: 
        - sh
        - -c
        - |
          while true; do 
            echo Pulling
            cd /app && git pull && sleep 60; 
          done
      # List of volumes
      volumes:
        - name: nginx-vol
          emptyDir: {}
